import re

def regex(acr):
    return re.compile(r'^[^.]*' + re.escape(acr) + r' [0-9]')

courts = [
        {'name':'Alabama', 'acronym':'Ala.'},
        {'name':'Alaska', 'acronym':'Alaska'},
        {'name':'Arizona', 'acronym':'Ariz.'},
        {'name':'California', 'acronym':'Cal.'},
        {'name':'California', 'acronym':'Cal. Ct. App.'},
        {'name':'California', 'acronym':'Cal. Sup. Ct.'},
        {'name':'Colorado', 'acronym':'Colo.'},
        {'name':'Colorado', 'acronym':'Colo. O.P.D.J.'},
        {'name':'Colorado', 'acronym':'Ohio'},
        {'name':'Connecticut', 'acronym':'Conn.'},
        {'name':'Connecticut', 'acronym':'Conn. Ct. Err.'},
        {'name':'Delaware', 'acronym':'Del. Sup. Ct.'},
        {'name':'Delaware', 'acronym':'Del.'},
        {'name':'District of Columbia', 'acronym':'D.C.'},
        {'name':'Florida', 'acronym':'Fla.'},
        {'name':'Georgia', 'acronym':'Ga.'},
        {'name':'Hawaii', 'acronym':'Haw.'},
        {'name':'Idaho', 'acronym':'Idaho'},
        {'name':'Illinois', 'acronym':'Ill.'},
        {'name':'Indiana', 'acronym':'Ind.'},
        {'name':'Iowa', 'acronym':'Iowa'},
        {'name':'Kansas', 'acronym':'Kan.'},
        {'name':'Kansas', 'acronym':'Kansas Supreme Court'},
        {'name':'Kentucky', 'acronym':'Ky. Ct. App.'},
        {'name':'Kentucky', 'acronym':'Ky.'},
        {'name':'Louisiana', 'acronym':'Fla.'},
        {'name':'Louisiana', 'acronym':'La.'},
        {'name':'Maine', 'acronym':'Maine'},
        {'name':'Maine', 'acronym':'Me.'},
        {'name':'Maryland', 'acronym':'Md.'},
        {'name':'Massachusetts', 'acronym':'Mass.'},
        {'name':'Michigan', 'acronym':'Mich.'},
        {'name':'Minnesota', 'acronym':'Minn.'},
        {'name':'Mississippi', 'acronym':'Miss.'},
        {'name':'Mississippi', 'acronym':'Mo.'},
        {'name':'Montana', 'acronym':'Mont.'},
        {'name':'Nebraska', 'acronym':'Neb.'},
        {'name':'Nevada', 'acronym':'Nev.'},
        {'name':'New Hampshire', 'acronym':'N.H.'},
        {'name':'New Jersey', 'acronym':'N.J. Sup. Ct.'},
        {'name':'New Jersey', 'acronym':'N.J.'},
        {'name':'New Mexico', 'acronym':'N.M.'},
        {'name':'New York', 'acronym':'N.Y. Ct. App.'},
        {'name':'New York', 'acronym':'N.Y.'},
        {'name':'North Dakota', 'acronym':'N.D.'},
        {'name':'North Carolina', 'acronym':'N.C.'},
        {'name':'Northern Mariana Islands', 'acronym':'N. Mar. I.'},
        {'name':'Ohio', 'acronym':'Ohio'},
        {'name':'Oklahoma', 'acronym':'Okla. Crim. App.'},
        {'name':'Oregon', 'acronym':'Or.'},
        {'name':'Oregon', 'acronym':'Oregon Supreme Court'},
        {'name':'Pennsylvania', 'acronym':'Pa.'},
        {'name':'Rhode Island', 'acronym':'R.I.'},
        {'name':'South Carolina', 'acronym':'S.C.'},
        {'name':'South Dakota', 'acronym':'N.D.'},
        {'name':'South Dakota', 'acronym':'S.D.'},
        {'name':'Tennessee', 'acronym':'Tenn. Ct. Err. & App.'},
        {'name':'Tennessee', 'acronym':'Tenn.'},
        {'name':'Texas', 'acronym':'Tex. Crim. App'},
        {'name':'Utah', 'acronym':'Utah'},
        {'name':'Vermont', 'acronym':'Vt.'},
        {'name':'Virginia', 'acronym':'Va.'},
        {'name':'Washington', 'acronym':'Wash.'},
        {'name':'West Virginia', 'acronym':'W. Va.'},
        {'name':'Wisconsin', 'acronym':'Wis.'},
        {'name':'Wyoming', 'acronym':'Wyo.'},
        {'name':'U.S.', 'acronym':'U.S.'},
        {'name':'Dakota Territory', 'acronym':'Dakota'},
        {'name':'Tribal Jurisdictions', 'acronym':'Cherokee Sup. Ct.'},
        {'name':'Tribal Jurisdictions', 'acronym':'Cherokee Nation Sup. Ct.'},
        {'name':'Tribal Jurisdictions', 'acronym':'Eastern Band of Cherokee Indians Sup. Ct.'},
        {'name':'Tribal Jurisdictions', 'acronym':'Fort McDowell Yavapai Nation Sup. Ct.'},
        {'name':'Tribal Jurisdictions', 'acronym':'Ho-Chunk Nation Sup. Ct.'},
        {'name':'Tribal Jurisdictions', 'acronym':'Sac & Fox Nation Sup. Ct.'},
        {'name':'Virgin Islands', 'acronym':'V.I.'},
        {'name':'Puerto Rico', 'acronym':'P.R.'},
        {'name':'Navajo Nation', 'acronym':'Navajo Nation Sup. Ct.'},
        {'name':'Navajo Nation', 'acronym':'Navajo'},
        {'name':'Guam', 'acronym':'Guam'},
]
